// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: m1NBpNyVff55Zfidoo96K
// Component: LvhQB8PJLaq9
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsglcu7Rs72YfE } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: glcu7RS72yfE/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: m1NBpNyVff55Zfidoo96K/projectcss
import sty from "./PlasmicCartItem.module.css"; // plasmic-import: LvhQB8PJLaq9/css

import RecycleIcon from "./icons/PlasmicIcon__Recycle"; // plasmic-import: HHDZEpDMObZi/icon
import Secure2Icon from "./icons/PlasmicIcon__Secure2"; // plasmic-import: zI35n43pfqIG/icon
import shoe23NgUEzBMyAbQe from "./images/shoe23.png"; // plasmic-import: NgUEzBMyABQe/picture

export type PlasmicCartItem__VariantMembers = {};

export type PlasmicCartItem__VariantsArgs = {};
type VariantPropType = keyof PlasmicCartItem__VariantsArgs;
export const PlasmicCartItem__VariantProps = new Array<VariantPropType>();

export type PlasmicCartItem__ArgsType = {
  itemImg?: string;
  title?: React.ReactNode;
  productNumber?: React.ReactNode;
  size?: React.ReactNode;
  quantity?: React.ReactNode;
};

type ArgPropType = keyof PlasmicCartItem__ArgsType;
export const PlasmicCartItem__ArgProps = new Array<ArgPropType>(
  "itemImg",
  "title",
  "productNumber",
  "size",
  "quantity"
);

export type PlasmicCartItem__OverridesType = {
  root?: p.Flex<"div">;
  img?: p.Flex<typeof p.PlasmicImg>;
  link?: p.Flex<"a">;
};

export interface DefaultCartItemProps {
  itemImg?: string;
  title?: React.ReactNode;
  productNumber?: React.ReactNode;
  size?: React.ReactNode;
  quantity?: React.ReactNode;
  className?: string;
}

function PlasmicCartItem__RenderFunc(props: {
  variants: PlasmicCartItem__VariantsArgs;
  args: PlasmicCartItem__ArgsType;
  overrides: PlasmicCartItem__OverridesType;
  dataFetches?: PlasmicCartItem__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsglcu7Rs72YfE()
  });

  return (
    true ? (
      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(projectcss.all, projectcss.root_reset, sty.root)}
      >
        {true ? (
          <p.PlasmicImg
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={"auto" as const}
            displayMaxHeight={"none" as const}
            displayMaxWidth={"none" as const}
            displayMinHeight={"0" as const}
            displayMinWidth={"0" as const}
            displayWidth={"200px" as const}
            src={
              args.itemImg !== undefined
                ? args.itemImg
                : {
                    src: shoe23NgUEzBMyAbQe,
                    fullWidth: 450,
                    fullHeight: 450,
                    aspectRatio: undefined
                  }
            }
          />
        ) : null}
        {true ? (
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__p3JBw)}
          >
            <a
              data-plasmic-name={"link"}
              data-plasmic-override={overrides.link}
              className={classNames(projectcss.a, sty.link)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__vE4AT)}>
                {p.renderPlasmicSlot({
                  defaultContents: "Some Title",
                  value: args.title,
                  className: classNames(sty.slotTargetTitle)
                })}
              </div>
            </a>

            <div className={classNames(projectcss.all, sty.freeBox__cetHc)}>
              {p.renderPlasmicSlot({
                defaultContents: "#00000",
                value: args.productNumber,
                className: classNames(sty.slotTargetProductNumber)
              })}
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__i2XfC)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ofvEs
                )}
              >
                {"Size: "}
              </div>

              {p.renderPlasmicSlot({
                defaultContents: "11",
                value: args.size
              })}
            </div>

            <div className={classNames(projectcss.all, sty.freeBox___285Le)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hx09G
                )}
              >
                {"Quantity: "}
              </div>

              {p.renderPlasmicSlot({
                defaultContents: "1",
                value: args.quantity
              })}
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__hs8Av)}
            >
              <RecycleIcon
                className={classNames(projectcss.all, sty.svg__ksavj)}
                role={"img"}
              />

              <Secure2Icon
                className={classNames(projectcss.all, sty.svg__xj7OX)}
                role={"img"}
              />
            </p.Stack>
          </p.Stack>
        ) : null}
      </div>
    ) : null
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "img", "link"],
  img: ["img"],
  link: ["link"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: typeof p.PlasmicImg;
  link: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCartItem__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCartItem__VariantsArgs;
    args?: PlasmicCartItem__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicCartItem__Fetches;
  } & Omit<PlasmicCartItem__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicCartItem__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCartItem__ArgProps,
      internalVariantPropNames: PlasmicCartItem__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicCartItem__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCartItem";
  } else {
    func.displayName = `PlasmicCartItem.${nodeName}`;
  }
  return func;
}

export const PlasmicCartItem = Object.assign(
  // Top-level PlasmicCartItem renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    link: makeNodeComponent("link"),

    // Metadata about props expected for PlasmicCartItem
    internalVariantProps: PlasmicCartItem__VariantProps,
    internalArgProps: PlasmicCartItem__ArgProps
  }
);

export default PlasmicCartItem;
/* prettier-ignore-end */
