// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: m1NBpNyVff55Zfidoo96K
// Component: HrCA_7p3nRe1
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: m1NBpNyVff55Zfidoo96K/projectcss
import sty from "./PlasmicRating.module.css"; // plasmic-import: HrCA_7p3nRe1/css

import EmptyStarIcon from "./icons/PlasmicIcon__EmptyStar"; // plasmic-import: TcLDfBcAwTha/icon
import FullStarIcon from "./icons/PlasmicIcon__FullStar"; // plasmic-import: m3m2ld07vRan/icon
import HalfStarIcon from "./icons/PlasmicIcon__HalfStar"; // plasmic-import: W3BLK2IOphog/icon

export type PlasmicRating__VariantMembers = {
  rating:
    | "one"
    | "two"
    | "three"
    | "four"
    | "five"
    | "half"
    | "oneHalf"
    | "twoHalf"
    | "threeHalf"
    | "fourHalf";
};

export type PlasmicRating__VariantsArgs = {
  rating?: SingleChoiceArg<
    | "one"
    | "two"
    | "three"
    | "four"
    | "five"
    | "half"
    | "oneHalf"
    | "twoHalf"
    | "threeHalf"
    | "fourHalf"
  >;
};

type VariantPropType = keyof PlasmicRating__VariantsArgs;
export const PlasmicRating__VariantProps = new Array<VariantPropType>("rating");

export type PlasmicRating__ArgsType = {};
type ArgPropType = keyof PlasmicRating__ArgsType;
export const PlasmicRating__ArgProps = new Array<ArgPropType>();

export type PlasmicRating__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultRatingProps {
  rating?: SingleChoiceArg<
    | "one"
    | "two"
    | "three"
    | "four"
    | "five"
    | "half"
    | "oneHalf"
    | "twoHalf"
    | "threeHalf"
    | "fourHalf"
  >;
  className?: string;
}

function PlasmicRating__RenderFunc(props: {
  variants: PlasmicRating__VariantsArgs;
  args: PlasmicRating__ArgsType;
  overrides: PlasmicRating__OverridesType;
  dataFetches?: PlasmicRating__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(projectcss.all, projectcss.root_reset, sty.root)}
    >
      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "twoHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "oneHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "half")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "three")
            ? FullStarIcon
            : hasVariant(variants, "rating", "two")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "one")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg___0DNyx, {
          [sty.svg__rating_five___0DNyxi4VfP]: hasVariant(
            variants,
            "rating",
            "five"
          ),
          [sty.svg__rating_fourHalf___0DNyxzhlhQ]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),
          [sty.svg__rating_four___0DNyxTRgBp]: hasVariant(
            variants,
            "rating",
            "four"
          ),
          [sty.svg__rating_half___0DNyx7BJgy]: hasVariant(
            variants,
            "rating",
            "half"
          ),
          [sty.svg__rating_oneHalf___0DNyxm8Rrz]: hasVariant(
            variants,
            "rating",
            "oneHalf"
          ),
          [sty.svg__rating_one___0DNyxguYIm]: hasVariant(
            variants,
            "rating",
            "one"
          ),
          [sty.svg__rating_threeHalf___0DNyx2Rbr]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          ),
          [sty.svg__rating_three___0DNyxPDaCc]: hasVariant(
            variants,
            "rating",
            "three"
          ),
          [sty.svg__rating_twoHalf___0DNyxOJmPi]: hasVariant(
            variants,
            "rating",
            "twoHalf"
          ),
          [sty.svg__rating_two___0DNyxEsHqA]: hasVariant(
            variants,
            "rating",
            "two"
          )
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "twoHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "oneHalf")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "three")
            ? FullStarIcon
            : hasVariant(variants, "rating", "two")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__pbZn8, {
          [sty.svg__rating_five__pbZn8I4VfP]: hasVariant(
            variants,
            "rating",
            "five"
          ),
          [sty.svg__rating_fourHalf__pbZn8ZhlhQ]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),
          [sty.svg__rating_four__pbZn8TRgBp]: hasVariant(
            variants,
            "rating",
            "four"
          ),
          [sty.svg__rating_oneHalf__pbZn8M8Rrz]: hasVariant(
            variants,
            "rating",
            "oneHalf"
          ),
          [sty.svg__rating_threeHalf__pbZn82Rbr]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          ),
          [sty.svg__rating_three__pbZn8PDaCc]: hasVariant(
            variants,
            "rating",
            "three"
          ),
          [sty.svg__rating_twoHalf__pbZn8OJmPi]: hasVariant(
            variants,
            "rating",
            "twoHalf"
          ),
          [sty.svg__rating_two__pbZn8EsHqA]: hasVariant(
            variants,
            "rating",
            "two"
          )
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "twoHalf")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "three")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__hiesP, {
          [sty.svg__rating_five__hiesPi4VfP]: hasVariant(
            variants,
            "rating",
            "five"
          ),
          [sty.svg__rating_fourHalf__hiesPzhlhQ]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),
          [sty.svg__rating_four__hiesPtRgBp]: hasVariant(
            variants,
            "rating",
            "four"
          ),
          [sty.svg__rating_threeHalf__hiesP2Rbr]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          ),
          [sty.svg__rating_three__hiesPpDaCc]: hasVariant(
            variants,
            "rating",
            "three"
          ),
          [sty.svg__rating_twoHalf__hiesPoJmPi]: hasVariant(
            variants,
            "rating",
            "twoHalf"
          )
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__u8Pyy, {
          [sty.svg__rating_five__u8PyYi4VfP]: hasVariant(
            variants,
            "rating",
            "five"
          ),
          [sty.svg__rating_fourHalf__u8PyYzhlhQ]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),
          [sty.svg__rating_four__u8PyytRgBp]: hasVariant(
            variants,
            "rating",
            "four"
          ),
          [sty.svg__rating_threeHalf__u8Pyy2Rbr]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          )
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? HalfStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__rqJu, {
          [sty.svg__rating_five__rqJui4VfP]: hasVariant(
            variants,
            "rating",
            "five"
          ),
          [sty.svg__rating_fourHalf__rqJuzhlhQ]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          )
        })}
        role={"img"}
      />
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRating__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRating__VariantsArgs;
    args?: PlasmicRating__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicRating__Fetches;
  } & Omit<PlasmicRating__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicRating__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRating__ArgProps,
      internalVariantPropNames: PlasmicRating__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicRating__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRating";
  } else {
    func.displayName = `PlasmicRating.${nodeName}`;
  }
  return func;
}

export const PlasmicRating = Object.assign(
  // Top-level PlasmicRating renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicRating
    internalVariantProps: PlasmicRating__VariantProps,
    internalArgProps: PlasmicRating__ArgProps
  }
);

export default PlasmicRating;
/* prettier-ignore-end */
