// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: m1NBpNyVff55Zfidoo96K
// Component: hRJXOxqWVqxg
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Value from "../../Value"; // plasmic-import: 7pr-oMTovPPk/component
import Button from "../../Button"; // plasmic-import: RwhbLl_Om_ZC/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: m1NBpNyVff55Zfidoo96K/projectcss
import sty from "./PlasmicEmojiValueProps.module.css"; // plasmic-import: hRJXOxqWVqxg/css

import PlaneIcon from "./icons/PlasmicIcon__Plane"; // plasmic-import: ALWYvEyWzpoP/icon
import MenuIcon from "./icons/PlasmicIcon__Menu"; // plasmic-import: DmYYd1D1uHJ9/icon
import RightArrowIcon from "./icons/PlasmicIcon__RightArrow"; // plasmic-import: 1tYQBOFCODtW/icon
import DocumentIcon from "./icons/PlasmicIcon__Document"; // plasmic-import: rdkc6ULqbQw0/icon
import LockIcon from "./icons/PlasmicIcon__Lock"; // plasmic-import: xauW07Fwy87L/icon

export type PlasmicEmojiValueProps__VariantMembers = {};

export type PlasmicEmojiValueProps__VariantsArgs = {};
type VariantPropType = keyof PlasmicEmojiValueProps__VariantsArgs;
export const PlasmicEmojiValueProps__VariantProps =
  new Array<VariantPropType>();

export type PlasmicEmojiValueProps__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicEmojiValueProps__ArgsType;
export const PlasmicEmojiValueProps__ArgProps = new Array<ArgPropType>(
  "children"
);

export type PlasmicEmojiValueProps__OverridesType = {
  root?: p.Flex<"section">;
};

export interface DefaultEmojiValuePropsProps {
  children?: React.ReactNode;
  className?: string;
}

function PlasmicEmojiValueProps__RenderFunc(props: {
  variants: PlasmicEmojiValueProps__VariantsArgs;
  args: PlasmicEmojiValueProps__ArgsType;
  overrides: PlasmicEmojiValueProps__OverridesType;
  dataFetches?: PlasmicEmojiValueProps__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <section
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(projectcss.all, projectcss.root_reset, sty.root)}
    >
      {p.renderPlasmicSlot({
        defaultContents: (
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__n7F7J)}
          >
            <Value
              children2={
                <Button
                  className={classNames("__wab_instance", sty.button__zikTq)}
                  colors={"black" as const}
                  endIcon={
                    <RightArrowIcon
                      className={classNames(projectcss.all, sty.svg__eglPq)}
                      role={"img"}
                    />
                  }
                  rounded={"rounded" as const}
                  size={"large" as const}
                >
                  {"Read our letter"}
                </Button>
              }
              className={classNames("__wab_instance", sty.value__bJvV2)}
              icon={
                <PlaneIcon
                  className={classNames(projectcss.all, sty.svg__aJaFu)}
                  role={"img"}
                />
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vxsn
                )}
              >
                {"Worldwide shipping"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dQk80
                )}
              >
                {"Special financing and earn rewards."}
              </div>
            </Value>

            <Value
              children2={
                <Button
                  className={classNames("__wab_instance", sty.button__ny4Tt)}
                  colors={"black" as const}
                  endIcon={
                    <RightArrowIcon
                      className={classNames(projectcss.all, sty.svg__hptg8)}
                      role={"img"}
                    />
                  }
                  rounded={"rounded" as const}
                  size={"large" as const}
                >
                  {"Read our letter"}
                </Button>
              }
              className={classNames("__wab_instance", sty.value__rjeLj)}
              icon={
                <DocumentIcon
                  className={classNames(projectcss.all, sty.svg__bm97Q)}
                  role={"img"}
                />
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__iIwJp
                )}
              >
                {"30-day guarantee"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___6UHwj
                )}
              >
                {"Free return policy."}
              </div>
            </Value>

            <Value
              children2={
                <Button
                  className={classNames("__wab_instance", sty.button__lk84I)}
                  colors={"black" as const}
                  endIcon={
                    <RightArrowIcon
                      className={classNames(projectcss.all, sty.svg__mvTe5)}
                      role={"img"}
                    />
                  }
                  rounded={"rounded" as const}
                  size={"large" as const}
                >
                  {"Read our letter"}
                </Button>
              }
              className={classNames("__wab_instance", sty.value__qRhcO)}
              icon={
                <LockIcon
                  className={classNames(projectcss.all, sty.svg__mf13U)}
                  role={"img"}
                />
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vnDWs
                )}
              >
                {"Secured payments"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__q2Ja7
                )}
              >
                {"We accept major credit cards."}
              </div>
            </Value>
          </p.Stack>
        ),

        value: args.children
      })}
    </section>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "section";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicEmojiValueProps__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicEmojiValueProps__VariantsArgs;
    args?: PlasmicEmojiValueProps__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicEmojiValueProps__Fetches;
  } & Omit<PlasmicEmojiValueProps__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicEmojiValueProps__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicEmojiValueProps__ArgProps,
      internalVariantPropNames: PlasmicEmojiValueProps__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicEmojiValueProps__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicEmojiValueProps";
  } else {
    func.displayName = `PlasmicEmojiValueProps.${nodeName}`;
  }
  return func;
}

export const PlasmicEmojiValueProps = Object.assign(
  // Top-level PlasmicEmojiValueProps renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicEmojiValueProps
    internalVariantProps: PlasmicEmojiValueProps__VariantProps,
    internalArgProps: PlasmicEmojiValueProps__ArgProps
  }
);

export default PlasmicEmojiValueProps;
/* prettier-ignore-end */
