// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: m1NBpNyVff55Zfidoo96K
// Component: BsbjgAjpCS2J
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBar from "../../NavBar"; // plasmic-import: SDaEQZxE2LvS/component
import Button from "../../Button"; // plasmic-import: RwhbLl_Om_ZC/component
import ProductCard from "../../ProductCard"; // plasmic-import: Jw8LASADv3c6/component
import Rating from "../../Rating"; // plasmic-import: HrCA_7p3nRe1/component
import Footer from "../../Footer"; // plasmic-import: tq70WOqYWkeM/component

import { useScreenVariants as useScreenVariantsglcu7Rs72YfE } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: glcu7RS72yfE/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: m1NBpNyVff55Zfidoo96K/projectcss
import sty from "./PlasmicCategory.module.css"; // plasmic-import: BsbjgAjpCS2J/css

import MenuIcon from "./icons/PlasmicIcon__Menu"; // plasmic-import: DmYYd1D1uHJ9/icon
import FilledCircleIcon from "./icons/PlasmicIcon__FilledCircle"; // plasmic-import: fXxLmLXqNYcn/icon
import EmptyCircleIcon from "./icons/PlasmicIcon__EmptyCircle"; // plasmic-import: F2QAk3SzSySi/icon
import shoe2F8DgGt33IiX from "./images/shoe2.png"; // plasmic-import: f8DgGT33Ii_x/picture
import shoe3ZFhFoMhGaAbE from "./images/shoe3.png"; // plasmic-import: zFhFOMhGaAbE/picture
import shoe4Jncp3AnUyfqy from "./images/shoe4.png"; // plasmic-import: jncp3AnUYFQY/picture
import shoe5Dw6Kw0TaWsEk from "./images/shoe5.png"; // plasmic-import: Dw6kw0taWSEk/picture
import shoe6J2I9NfIEvAc from "./images/shoe6.png"; // plasmic-import: J2I9Nf_iEvAc/picture
import shoe7Q9Ik7PICq3H from "./images/shoe7.png"; // plasmic-import: Q9ik7p-iCq3H/picture
import shoe81Iu0GoOvUlgr from "./images/shoe8.png"; // plasmic-import: 1Iu0GoOvUlgr/picture
import shoe9QZoyTkePlRwl from "./images/shoe9.png"; // plasmic-import: QZoyTKEPlRwl/picture
import shoe10WpkPuQj8Lw2M from "./images/shoe10.png"; // plasmic-import: wpkPuQJ8Lw2m/picture
import shoe11NPuRilhidQss from "./images/shoe11.png"; // plasmic-import: NPuRILHIDQss/picture
import shoe12Njqu2HLNpKxP from "./images/shoe12.png"; // plasmic-import: Njqu2hLNpKxP/picture
import shoe13ORsj01D97Qy from "./images/shoe13.png"; // plasmic-import: ORsj01D-97Qy/picture
import shoe14JDryz8O42G9O from "./images/shoe14.png"; // plasmic-import: JDryz8o42g9o/picture
import shoe15TvxOlJZp6H6M from "./images/shoe15.png"; // plasmic-import: tvxOlJZp6h6M/picture
import shoe16A9T2EiD57Cc from "./images/shoe16.png"; // plasmic-import: a9T2EiD57-cc/picture
import shoe17ClpzGeqQGfdY from "./images/shoe17.png"; // plasmic-import: ClpzGeqQGfdY/picture

export type PlasmicCategory__VariantMembers = {};

export type PlasmicCategory__VariantsArgs = {};
type VariantPropType = keyof PlasmicCategory__VariantsArgs;
export const PlasmicCategory__VariantProps = new Array<VariantPropType>();

export type PlasmicCategory__ArgsType = {};
type ArgPropType = keyof PlasmicCategory__ArgsType;
export const PlasmicCategory__ArgProps = new Array<ArgPropType>();

export type PlasmicCategory__OverridesType = {
  root?: p.Flex<"div">;
  navBar?: p.Flex<typeof NavBar>;
  section?: p.Flex<"section">;
  container6?: p.Flex<"div">;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultCategoryProps {
  className?: string;
}

function PlasmicCategory__RenderFunc(props: {
  variants: PlasmicCategory__VariantsArgs;
  args: PlasmicCategory__ArgsType;
  overrides: PlasmicCategory__OverridesType;
  dataFetches?: PlasmicCategory__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsglcu7Rs72YfE()
  });

  return (
    <React.Fragment>
      {}
      {}

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
            searchOpen={"searchOpen" as const}
          />

          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"container6"}
              data-plasmic-override={overrides.container6}
              hasGap={true}
              className={classNames(projectcss.all, sty.container6)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__avAb)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__wSnVx)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jVdI
                    )}
                  >
                    {"Categories"}
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__atfsi)}
                    states={"active" as const}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rtImv
                      )}
                    >
                      {"All"}
                    </div>
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__hYsz)}
                  >
                    {"New"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__cGltE)}
                  >
                    {"Womens"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__qo2Lo)}
                  >
                    {"Mens"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__ntRvm)}
                  >
                    {"Kids"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__anBv6)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tg9Ut
                      )}
                    >
                      {"On sale"}
                    </div>
                  </Button>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__aPmRw)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3Png
                    )}
                  >
                    {"Price"}
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__qi0N)}
                  >
                    {"$0 - $50"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__rmkj9)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eziRa
                      )}
                    >
                      {"$51 - $99"}
                    </div>
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__wlF2)}
                  >
                    {"$101+"}
                  </Button>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__pWpL0)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wLGz
                    )}
                  >
                    {"Colors"}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__ie0Js)}
                  >
                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(projectcss.all, sty.svg__bjop4)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__v0Q0F
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(projectcss.all, sty.svg__htPaL)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__neHvl
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(projectcss.all, sty.svg__mEwF)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iXzdZ
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(projectcss.all, sty.svg__qKl8W)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yMpvp
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___1H6Ow
                          )}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xj8Wq
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(projectcss.all, sty.svg__ddQrv)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__dxcEl
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(projectcss.all, sty.svg__ccmAm)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__krYdS
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(projectcss.all, sty.svg__j1X0N)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___9MVn2
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(projectcss.all, sty.svg__mfAV)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__g4PM5
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(projectcss.all, sty.svg__q1Kd2)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pcKt
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___8BvVl
                          )}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ekVwo
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(projectcss.all, sty.svg__gnbfI)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mHsNx
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___4OiDt
                          )}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ckIw
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <FilledCircleIcon
                          className={classNames(projectcss.all, sty.svg__nscAe)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__cr6KT
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>

                    <Button
                      iconOnly={"iconOnly" as const}
                      size={"narrow" as const}
                      startIcon={
                        <EmptyCircleIcon
                          className={classNames(projectcss.all, sty.svg__xX3Gv)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__p5Hlt
                        )}
                      >
                        {"Adidas"}
                      </div>
                    </Button>
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__p544K)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eiS1
                    )}
                  >
                    {"Brands"}
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__hoopR)}
                  >
                    {"Adidas"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__z9RgJ)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qsey3
                      )}
                    >
                      {"Asics"}
                    </div>
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__sNeGo)}
                  >
                    {"Crocs"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__vomVn)}
                  >
                    {"Fila"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__g14L)}
                  >
                    {"Nike"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button__xx11G)}
                  >
                    {"Puma"}
                  </Button>

                  <Button
                    className={classNames("__wab_instance", sty.button___56Kst)}
                  >
                    {"Reebok"}
                  </Button>
                </p.Stack>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__kx0Xd)}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__rrj0T
                  )}
                  img={{
                    src: shoe2F8DgGt33IiX,
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__z4AfE
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38 Limited Edition"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___20JKq
                    )}
                  >
                    {"Women's Running Shoe"}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__on9Ho
                  )}
                  img={{
                    src: shoe3ZFhFoMhGaAbE,
                    fullWidth: 964,
                    fullHeight: 898,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kzfBn
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__b7KFf
                    )}
                  >
                    {"Continue the NMD legacy in these adidas NMD_R1 Shoes."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__iPipE
                  )}
                  img={{
                    src: shoe4Jncp3AnUyfqy,
                    fullWidth: 1024,
                    fullHeight: 768,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__varui
                    )}
                  >
                    {"Question Low Men's Basketball Shoes"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yrjS0
                    )}
                  >
                    {"Lace up fierce baller style."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___11Ia
                  )}
                  img={{
                    src: shoe5Dw6Kw0TaWsEk,
                    fullWidth: 2000,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__e8Lvl
                    )}
                  >
                    {"Cali Women's Sneakers"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__g614
                    )}
                  >
                    {"A sport style turned street classic."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__gsoaT
                  )}
                  img={{
                    src: shoe6J2I9NfIEvAc,
                    fullWidth: 320,
                    fullHeight: 320,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eyAmp
                    )}
                  >
                    {"MAGIC SPEED"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zLSn
                    )}
                  >
                    {"mMade for racing or regular training runs."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__zd5Rt
                  )}
                  img={{
                    src: shoe7Q9Ik7PICq3H,
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aXqi
                    )}
                  >
                    {"Pride Chuck Taylor All Star"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__htyIc
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__oVfLv
                  )}
                  img={{
                    src: shoe81Iu0GoOvUlgr,
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qRwpc
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rodYz
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__v8Cnj
                  )}
                  img={{
                    src: shoe9QZoyTkePlRwl,
                    fullWidth: 1024,
                    fullHeight: 768,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3KSle
                    )}
                  >
                    {"GEL-Nimbus 22 Retro Tokyo"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1Ufb
                    )}
                  >
                    {"Enjoy comfort with each stride."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__haVs7
                  )}
                  img={{
                    src: shoe10WpkPuQj8Lw2M,
                    fullWidth: 964,
                    fullHeight: 898,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vBknc
                    )}
                  >
                    {"A Bug's World Chuck Taylor All Star"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kRusa
                    )}
                  >
                    {"Allover glow-in-the-dark bug prints."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__n6D4Y
                  )}
                  img={{
                    src: shoe11NPuRilhidQss,
                    fullWidth: 766,
                    fullHeight: 766,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tLj2U
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rJtIq
                    )}
                  >
                    {
                      "Effortlessly step up your look than a pop of animal print."
                    }
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__vHrLt
                  )}
                  img={{
                    src: shoe12Njqu2HLNpKxP,
                    fullWidth: 2000,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vRsjw
                    )}
                  >
                    {"Suede Teams Little Kids' Shoes"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ubsit
                    )}
                  >
                    {"Worn by the icons of every generation."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__yyie3
                  )}
                  img={{
                    src: shoe13ORsj01D97Qy,
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cjbn
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__s9Xs1
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__fNCo
                  )}
                  img={{
                    src: shoe14JDryz8O42G9O,
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nkIvv
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cZxYi
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__nnQbk
                  )}
                  img={{
                    src: shoe15TvxOlJZp6H6M,
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uxu9M
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__p4SFf
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__wsz6B
                  )}
                  img={{
                    src: shoe16A9T2EiD57Cc,
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rpBna
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kVd6
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___8SLfM
                  )}
                  img={{
                    src: shoe17ClpzGeqQGfdY,
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  link={"/item" as const}
                  small={"small" as const}
                  tags={
                    <Button
                      colors={"lightGray" as const}
                      size={"small" as const}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__k7Kf4
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gEr0G
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>
              </p.Stack>
            </p.Stack>
          </section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "navBar", "section", "container6", "footer"],
  navBar: ["navBar"],
  section: ["section", "container6"],
  container6: ["container6"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  navBar: typeof NavBar;
  section: "section";
  container6: "div";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCategory__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCategory__VariantsArgs;
    args?: PlasmicCategory__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicCategory__Fetches;
  } & Omit<PlasmicCategory__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicCategory__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCategory__ArgProps,
      internalVariantPropNames: PlasmicCategory__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicCategory__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCategory";
  } else {
    func.displayName = `PlasmicCategory.${nodeName}`;
  }
  return func;
}

export const PlasmicCategory = Object.assign(
  // Top-level PlasmicCategory renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    section: makeNodeComponent("section"),
    container6: makeNodeComponent("container6"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicCategory
    internalVariantProps: PlasmicCategory__VariantProps,
    internalArgProps: PlasmicCategory__ArgProps
  }
);

export default PlasmicCategory;
/* prettier-ignore-end */
